### ISSUE TITLE
Merging in map.jinja not working as expected

### ISSUE THREAD

**Issue by oznah** [oznah/slurm-formula#1]
The general idea, much like other's formulas, is that a base set of defaults (defaults.yaml) are declared which can be overwritten/merged with OS specific settings, which can be overwritten/merged with user provided pillar data. The OS specific setting would be in osmap.yaml. Currently I haven't tested on any OS other than RHEL, but it is possible that we would need something different for a different OS. The problem is, when I add key/value pairs in the osmap, it breaks the rendering of the defaults (ie. it doesn't merge, it overwrites).

Example:
```
cat defaults.yaml

slurm:
  global:
    ControlMachine: linux0
    MpiDefault: none
    ProctrackType: proctrack/pgid
    ReturnToService: 1
    SlurmctldPidFile: /var/run/slurmctld.pid
    SlurmdPidFile: /var/run/slurmd.pid
    SlurmdSpoolDir: /var/spool/slurmd
    SlurmUser: slurm
```

In this example if I wanted to override SlurmUser and I put the following in slurm pillar, it works as expected. 

```
cat pillar/slurm/init.sls

slurm:
  global:
    SlurmUser: foo
```

The place where this info is used slurm/files/slurm.conf.jinja, renders the config correctly and you would get.

```
cat /etc/slurm/slurm.conf

# Dynamic slurm.conf file generated by salt-minion(1)
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN


## BASE ##
ControlMachine=linux0
MpiDefault=none
ProctrackType=proctrack/pgid
ReturnToService=1
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=foo
```

But if I try to override that default setting in the osmap. The conf file gets mangled. Ie. it removes everything except what I specify in the osmap. It doesn't merge.

Example

```
cat osmap.yaml

RedHat:
  slurm:
    global:
      SlurmUser: foo
```

The above would render the config file like so, assuming nothing is in the pillar.

```
cat /etc/slurm/slurm.conf

# Dynamic slurm.conf file generated by salt-minion(1)
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN


## BASE ##
SlurmUser=foo
```

This must be something simple. It has something to do with the nested yaml defaults, but I can get it to do what I think it should. Any help would be greatly appreciated.

**Comment by whiteinge** [comment]
From a quick reading, I think the trouble is the [`update()` call](https://github.com/oznah/slurm-formula/blob/12005e1/slurm/map.jinja#L8) in the middle because Python's native `update` method does not operate recursively so the `global` sub-dictionary in `defaults` is replaced entirely by the contents of `osfam`.

I think the quickest way to tackle this is to pass `defaults` as the [`base` argument to `grains.filter_by`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by).

**Comment by oznah** [comment]
@whiteinge  Wouldn't that skip any OS specific overrides/differences?

**Comment by oznah** [comment]
I am not sure this is the best way, but this should have fixed this issue

commit: 66cebb0aa6dfc6bfb730d6a1bfd5fd6839093a2c

**Comment by whiteinge** [comment]
Doh. Sorry for the slow reply. I didn't get an email from GH for your first reply. :frowning:

You might be right about that. Think I'd have to try first to be sure. If that doesn't doesn't do the trick you'll need another way to perform the recursive merge. We recently exposed an execution module to do that: [slsutil.merge](https://github.com/saltstack/salt/blob/d11011/salt/modules/slsutil.py#L22-L38). But that won't be in a Salt release until (I think) the Carbon release...

**Comment by oznah** [comment]
@whiteinge checkout this merge (commit: [66cebb0](https://github.com/oznah/slurm-formula/commit/66cebb0aa6dfc6bfb730d6a1bfd5fd6839093a2c)). This seems to fix it. You have to format the osmap like so for it to work. Basically the yaml need the whole hierarchy to merge it correctly.

```
cat osmap.yaml

RedHat:
  slurm:
    global:
      SlurmUser: foo
```
